[package]
name = "rocket-okapi"
version = "0.1.0"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.1.6"
okapi = { version = "0.1.0", path = "../okapi" }
rocket = { version = "0.4.2", default-features = false }

[dependencies.rocket_contrib] # TODO remove
version = "0.4.2"
default-features = false
features = ["json"]
