[package]
name = "rocket_okapi_codegen"
description = "Macros supporting rocket_okapi"
repository = "https://github.com/GREsau/okapi"
version = "0.1.1"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"
license = "MIT"
keywords = ["rust", "openapi", "swagger", "rocket"]

[lib]
proc-macro = true

[dependencies]
rocket_http = "0.4.2"
darling = "0.9.0"
syn = "0.15.44"
proc-macro2 = "0.4.30"
quote = "0.6.13"
