[package]
name = "rocket_okapi_codegen"
version = "0.1.0"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
rocket_http = "0.4.2"
darling = "0.9.0"
syn = "0.15.44"
proc-macro2 = "0.4.30"
quote = "0.6.13"
