[package]
name = "okapi"
version = "0.1.0"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"

[features]
make_schema = []

[dependencies]
schemars = "0.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
